# GitLab CI/CD 配置文件
# 用于自动构建和部署 Vue 3 + Vite 项目到 GitLab Pages

# 定义构建阶段
stages:
  - build
  - deploy

# 定义缓存，加速构建
cache:
  paths:
    - node_modules/

# 构建任务
build:
  stage: build
  image: node:18
  script:
    - echo "开始安装依赖..."
    - npm ci --prefer-offline --no-audit
    - echo "开始类型检查..."
    - npm run type-check
    - echo "开始构建项目..."
    - npm run build
    - echo "构建完成！"
  artifacts:
    paths:
      - dist/
    expire_in: 1 hour
  only:
    - main
    - master
    - develop

# 部署到 GitLab Pages
pages:
  stage: deploy
  image: alpine:latest
  script:
    - echo "准备部署到 GitLab Pages..."
    - rm -rf public
    - mv dist public
    - echo "部署完成！"
  artifacts:
    paths:
      - public
  only:
    - main
    - master
  dependencies:
    - build

# 可选：预览部署（用于其他分支）
preview:
  stage: deploy
  image: alpine:latest
  script:
    - echo "创建预览环境..."
    - rm -rf public
    - mv dist public
  artifacts:
    paths:
      - public
  environment:
    name: preview/$CI_COMMIT_REF_NAME
    url: https://$CI_PROJECT_NAMESPACE.gitlab.io/-/$CI_PROJECT_NAME/-/jobs/$CI_JOB_ID/artifacts/public/index.html
  only:
    - develop
  dependencies:
    - build
  when: manual
